<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="guille" failures="2" tests="4" name="LoginTest" time="19.101" errors="0" timestamp="2022-06-09T01:26:35 CEST">
  <testcase classname="tests.LoginTests" name="invalidLoginTest_InvalidUserNameInvalidPassword" time="4.227">
    <skipped/>
  </testcase> <!-- invalidLoginTest_InvalidUserNameInvalidPassword -->
  <testcase classname="tests.LoginTests" name="invalidLoginTest_InvalidUserNameInvalidPassword" time="6.981">
    <failure type="org.openqa.selenium.UnsupportedCommandException" message="HTTP method not allowed
Command duration or timeout: 9 milliseconds
Build info: version: &amp;apos;4.2.1&amp;apos;, revision: &amp;apos;ac4d0fdd4a&amp;apos;
System info: host: &amp;apos;guille&amp;apos;, ip: &amp;apos;192.168.0.151&amp;apos;, os.name: &amp;apos;Linux&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;5.4.0-110-generic&amp;apos;, java.version: &amp;apos;11.0.15&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [3f6bd37f-0406-433d-be6b-8f7e146ec5df, getLog {type=browser}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 100.0, moz:accessibilityChecks: false, moz:buildID: 20220428192727, moz:debuggerAddress: localhost:34263, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 26647, moz:profile: /tmp/rust_mozprofile7OUUl0, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platformName: LINUX, platformVersion: 5.4.0-110-generic, proxy: Proxy(), se:cdp: ws://localhost:34263/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 3f6bd37f-0406-433d-be6b-8f7e146ec5df">
      <![CDATA[org.openqa.selenium.UnsupportedCommandException: HTTP method not allowed
Command duration or timeout: 9 milliseconds
Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
System info: host: 'guille', ip: '192.168.0.151', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-110-generic', java.version: '11.0.15'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [3f6bd37f-0406-433d-be6b-8f7e146ec5df, getLog {type=browser}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 100.0, moz:accessibilityChecks: false, moz:buildID: 20220428192727, moz:debuggerAddress: localhost:34263, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 26647, moz:profile: /tmp/rust_mozprofile7OUUl0, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platformName: LINUX, platformVersion: 5.4.0-110-generic, proxy: Proxy(), se:cdp: ws://localhost:34263/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 3f6bd37f-0406-433d-be6b-8f7e146ec5df
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:217)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:169)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:40)
at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:81)
at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
at utils.logs.JSErrorLogs.isLoginErrorLog(JSErrorLogs.java:13)
at pages.LoginPage.verifyLogError(LoginPage.java:58)
at tests.LoginTests.invalidLoginTest_InvalidUserNameInvalidPassword(LoginTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest_InvalidUserNameInvalidPassword -->
  <testcase classname="tests.LoginTests" name="invalidLoginTest_EmptyUserEmptyPassword" time="2.057">
    <skipped/>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
  <testcase classname="tests.LoginTests" name="invalidLoginTest_EmptyUserEmptyPassword" time="1.94">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Bu alan覺n doldurulmas覺 zorunludur.&amp;gt; but was:&amp;lt;WRONG MESSAGE FOR FAILURE!&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Bu alan覺n doldurulmas覺 zorunludur.> but was:<WRONG MESSAGE FOR FAILURE!>
at pages.LoginPage.verifyLoginPassword(LoginPage.java:51)
at tests.LoginTests.invalidLoginTest_EmptyUserEmptyPassword(LoginTests.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
</testsuite> <!-- LoginTest -->
